Repository andela/ah-backend-valkyrie, pull requests merged in 2019-02, with the labels that each got.

#34 #162633507 Ft favorite articles
  .gitignore
  README.md
  authors/apps/articles/helper.py
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/migrations/0002_auto_20190124_1615.py
  authors/apps/articles/tests/test_articles.py
  authors/apps/articles/tests/test_favorites.py
  authors/apps/articles/views.py
  authors/apps/authentication/migrations/0001_initial.py
  authors/apps/authentication/migrations/0002_auto_20190124_1515.py
  authors/apps/authentication/migrations/0003_auto_20190124_1557.py
  authors/apps/authentication/tests/base.py
  authors/apps/authentication/urls.py
  authors/apps/profiles/migrations/0001_initial.py
  authors/urls.py
Labels: Finished, awaiting LGTMs

#35 #162633515 Add a bookmark functionality for articles
  README.md
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_bookmarks.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
  authors/apps/authentication/migrations/0001_initial.py
  authors/apps/authentication/tests/base.py
  authors/apps/core/authority.py
  authors/apps/profiles/migrations/0001_initial.py
Labels: Finished, awaiting LGTMs

#31 #162633511 Feat pagination support
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/pagination.py
  authors/apps/articles/tests/test_pagination.py
  authors/apps/articles/views.py
  authors/apps/ratings/migrations/0001_initial.py
Labels: Finished, pending merge

#33 162633520 Feat reading stats
  authors/apps/articles/helper.py
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_stats.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
  authors/apps/authentication/migrations/0001_initial.py
  authors/apps/authentication/migrations/0002_auto_20190124_1515.py
  authors/apps/authentication/migrations/0003_auto_20190124_1557.py
  authors/apps/authentication/tests/base.py
  authors/apps/comments/migrations/0001_initial.py
  authors/apps/comments/migrations/0002_commenthistory.py
  authors/apps/comments/migrations/0002_commentreaction.py
  authors/apps/profiles/migrations/0001_initial.py
  authors/apps/ratings/migrations/0001_initial.py
  authors/apps/ratings/migrations/0002_auto_20190121_1639.py
  authors/apps/ratings/migrations/0003_auto_20190123_1512.py
Labels: pending merge

#37 162633517 Feat highlight and comment
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_highlight.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
  authors/apps/authentication/migrations/0001_initial.py
  authors/apps/authentication/tests/base.py
  authors/apps/comments/migrations/0001_initial.py
  authors/apps/profiles/migrations/0001_initial.py
  authors/apps/ratings/migrations/0001_initial.py
Labels: pending merge

#27 162633505 Ft like or dislike articles
  .gitignore
  .travis.yml
  README.md
  authors/apps/articles/helper.py
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/models.py
  authors/apps/articles/renderers.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_articles.py
  authors/apps/articles/tests/test_favorites.py
  authors/apps/articles/tests/test_like_articles.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
  authors/apps/authentication/migrations/0001_initial.py
  authors/apps/authentication/models.py
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests/base.py
  authors/apps/authentication/tests/test_jwt_auth.py
  authors/apps/authentication/tests/test_user_sign_up_validation_errors.py
  authors/apps/authentication/urls.py
  authors/apps/authentication/views.py
  authors/apps/comments/api_views.py
  authors/apps/comments/models.py
  authors/apps/comments/serializers.py
  authors/apps/comments/tests/test_comments.py
  authors/urls.py
Labels: awaiting LGTMs

#41 162633516 Ft report article
  .travis.yml
  README.md
  authors/apps/articles/helper.py
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_like_articles.py
  authors/apps/articles/tests/test_report_articles.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
  authors/apps/authentication/backends.py
  authors/apps/authentication/models.py
  authors/apps/authentication/tests/base.py
  authors/apps/authentication/tests/test_jwt_auth.py
  authors/apps/authentication/urls.py
  authors/apps/authentication/views.py
  authors/apps/core/authority.py
  authors/settings.py
  authors/urls.py
Labels: awaiting LGTMs
